import type { ToolDefinition } from "@/types/tool";

const commonFaqs = [
  {
    question: "Are my images uploaded to a server?",
    answer:
      "Core tools run in your browser. For the MVP flow, Kompresio processes previews, compression, conversion, resizing, metadata cleaning, and ZIP export locally on your device.",
  },
  {
    question: "Can I process multiple images?",
    answer:
      "Yes. You can add multiple files to the queue, process them together, and download the results individually or as a ZIP archive.",
  },
  {
    question: "Does compression reduce quality?",
    answer:
      "Lossy formats can reduce quality if the quality value is too low. The balanced presets use practical values for smaller files while keeping the image visually clean.",
  },
];

export const tools: ToolDefinition[] = [
  {
    slug: "compress-image",
    name: "Compress Image",
    title: "Compress Image Online — Fast and Private",
    description:
      "Compress JPG, PNG, and WebP images online with Kompresio. Fast, private, browser-based image compression with batch ZIP download support.",
    h1: "Compress Image Online",
    eyebrow: "Image compressor",
    icon: "gauge",
    mode: "compress",
    primaryAction: "Compress image",
    primaryKeyword: "compress image online",
    category: "Compression",
    supportedFormats: ["JPG", "PNG", "WebP", "AVIF", "GIF", "SVG"],
    benefits: [
      "Reduce file size before website, email, form, or marketplace uploads.",
      "Preview original and optimized output before download.",
      "Strip metadata during export for a cleaner file.",
    ],
    steps: [
      "Upload one or more images.",
      "Choose a quality preset or set quality manually.",
      "Preview the output and download a single image or ZIP.",
    ],
    useCases: ["Websites", "Documents", "Marketplace photos", "Email attachments"],
    related: ["convert-to-webp", "resize-image", "metadata-cleaner", "batch-converter"],
    faqs: commonFaqs,
  },
  {
    slug: "compress-jpg",
    name: "Compress JPG",
    title: "Compress JPG Online — Fast and Private",
    description:
      "Reduce JPG photo size directly in your browser with Kompresio. Choose quality, resize large images, clean metadata, and export optimized results.",
    h1: "Compress JPG Online",
    eyebrow: "JPG compressor",
    icon: "image",
    mode: "compress",
    primaryAction: "Compress JPG",
    primaryKeyword: "compress JPG online",
    category: "Compression",
    supportedFormats: ["JPG", "JPEG"],
    benefits: [
      "Make large camera photos easier to upload.",
      "Use smart WebP recommendations when JPG files are too large.",
      "Remove hidden camera details from exported files.",
    ],
    steps: ["Upload JPG files.", "Pick balanced or high quality.", "Download optimized JPG or WebP output."],
    useCases: ["Forms", "Product photos", "Portfolio images"],
    related: ["compress-image", "jpg-to-webp", "resize-image", "metadata-cleaner"],
    faqs: commonFaqs,
  },
  {
    slug: "compress-png",
    name: "Compress PNG",
    title: "Compress PNG Online — Fast and Private",
    description:
      "Compress PNG images and convert transparent PNGs to high-quality WebP directly in your browser with Kompresio.",
    h1: "Compress PNG Online",
    eyebrow: "PNG compressor",
    icon: "image",
    mode: "compress",
    primaryAction: "Compress PNG",
    primaryKeyword: "compress PNG online",
    category: "Compression",
    supportedFormats: ["PNG"],
    benefits: [
      "Optimize screenshots, UI assets, and transparent graphics.",
      "Preserve transparency when exporting WebP.",
      "Batch process PNG assets for websites.",
    ],
    steps: ["Upload PNG files.", "Keep PNG or export WebP.", "Download clean optimized files."],
    useCases: ["Screenshots", "Transparent assets", "UI icons"],
    related: ["compress-image", "png-to-webp", "resize-image", "batch-converter"],
    faqs: commonFaqs,
  },
  {
    slug: "convert-to-webp",
    name: "Convert to WebP",
    title: "Convert Images to WebP Online — Fast and Private",
    description:
      "Convert JPG, PNG, and other images to WebP in your browser. Kompresio helps create lightweight WebP files for faster websites.",
    h1: "Convert Images to WebP",
    eyebrow: "WebP converter",
    icon: "refresh",
    mode: "webp",
    primaryAction: "Convert to WebP",
    primaryKeyword: "convert image to WebP",
    category: "Conversion",
    supportedFormats: ["JPG", "PNG", "WebP", "AVIF", "GIF", "SVG"],
    benefits: [
      "Create smaller web-ready images from JPG and PNG.",
      "Batch convert assets and export a structured ZIP.",
      "Use browser processing without sending images to a server.",
    ],
    steps: ["Upload images.", "Select WebP quality or lossless mode.", "Download .webp output."],
    useCases: ["Next.js assets", "Landing pages", "Blog images", "Product catalogs"],
    related: ["jpg-to-webp", "png-to-webp", "compress-image", "batch-converter"],
    faqs: commonFaqs,
  },
  {
    slug: "jpg-to-webp",
    name: "JPG to WebP",
    title: "JPG to WebP Converter — Fast and Private",
    description:
      "Convert JPG photos to WebP online with Kompresio. Reduce photo file size for websites while keeping visual quality.",
    h1: "JPG to WebP Converter",
    eyebrow: "Photo converter",
    icon: "refresh",
    mode: "webp",
    primaryAction: "Convert JPG to WebP",
    primaryKeyword: "JPG to WebP",
    category: "Conversion",
    supportedFormats: ["JPG", "JPEG"],
    benefits: [
      "Turn heavy JPG photos into compact WebP files.",
      "Use quality presets for web, marketplace, or documents.",
      "Rename output files with SEO-friendly names.",
    ],
    steps: ["Upload JPG files.", "Choose WebP quality.", "Download optimized WebP images."],
    useCases: ["Website galleries", "Hero images", "Blog covers"],
    related: ["convert-to-webp", "compress-jpg", "resize-image", "image-analyzer"],
    faqs: commonFaqs,
  },
  {
    slug: "png-to-webp",
    name: "PNG to WebP",
    title: "PNG to WebP Converter — Fast and Private",
    description:
      "Convert PNG images to WebP online. Preserve transparency and reduce image weight for modern websites.",
    h1: "PNG to WebP Converter",
    eyebrow: "Transparent asset converter",
    icon: "refresh",
    mode: "webp",
    primaryAction: "Convert PNG to WebP",
    primaryKeyword: "PNG to WebP",
    category: "Conversion",
    supportedFormats: ["PNG"],
    benefits: [
      "Create transparent WebP output from PNG assets.",
      "Reduce screenshots and UI graphics for faster pages.",
      "Process batches without server upload.",
    ],
    steps: ["Upload PNG files.", "Select high quality WebP.", "Download .webp files or ZIP."],
    useCases: ["Transparent product photos", "UI screenshots", "Website graphics"],
    related: ["convert-to-webp", "compress-png", "resize-image", "batch-converter"],
    faqs: commonFaqs,
  },
  {
    slug: "convert-to-avif",
    name: "Convert to AVIF",
    title: "AVIF Converter Online — Fast and Private",
    description:
      "Convert images to AVIF in supported browsers. Kompresio prepares modern image assets for performance-focused websites.",
    h1: "Convert Images to AVIF",
    eyebrow: "AVIF converter",
    icon: "zap",
    mode: "avif",
    primaryAction: "Convert to AVIF",
    primaryKeyword: "AVIF converter",
    category: "Conversion",
    supportedFormats: ["JPG", "PNG", "WebP", "AVIF"],
    benefits: [
      "Create highly compressed modern image output.",
      "Use browser support detection with clear fallback messaging.",
      "Good for experimental performance workflows.",
    ],
    steps: ["Upload an image.", "Choose AVIF output.", "Download when your browser supports AVIF encoding."],
    useCases: ["Core Web Vitals", "Modern landing pages", "Developer assets"],
    related: ["convert-to-webp", "compress-image", "image-analyzer", "batch-converter"],
    faqs: commonFaqs,
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    title: "Resize Image Online — Fast and Private",
    description:
      "Resize JPG, PNG, WebP, and AVIF images by width, height, percentage, or preset directly in your browser.",
    h1: "Resize Image Online",
    eyebrow: "Image resizer",
    icon: "resize",
    mode: "resize",
    primaryAction: "Resize image",
    primaryKeyword: "resize image online",
    category: "Resize",
    supportedFormats: ["JPG", "PNG", "WebP", "AVIF"],
    benefits: [
      "Resize for Instagram, YouTube, website hero images, and marketplace photos.",
      "Keep aspect ratio locked for clean output.",
      "Compress after resizing for smaller downloads.",
    ],
    steps: ["Upload images.", "Choose a preset or custom width.", "Export resized files."],
    useCases: ["Instagram posts", "YouTube thumbnails", "Blog covers", "Document uploads"],
    related: ["compress-image", "convert-to-webp", "crop-image", "batch-converter"],
    faqs: commonFaqs,
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    title: "Crop Image Online — Fast and Private",
    description:
      "Prepare images for common aspect ratios. Kompresio includes a crop-ready workflow for social, marketplace, and document images.",
    h1: "Crop Image Online",
    eyebrow: "Crop tool",
    icon: "crop",
    mode: "crop",
    primaryAction: "Crop image",
    primaryKeyword: "crop image online",
    category: "Resize",
    supportedFormats: ["JPG", "PNG", "WebP", "AVIF"],
    benefits: [
      "Use common aspect ratio targets for social media.",
      "Preview output before exporting.",
      "Combine crop planning with resize and compression settings.",
    ],
    steps: ["Upload an image.", "Choose an aspect target.", "Export optimized output."],
    useCases: ["Social media", "Marketplace photos", "Profile pictures"],
    related: ["resize-image", "compress-image", "convert-to-webp", "metadata-cleaner"],
    faqs: commonFaqs,
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    title: "HEIC to JPG Converter — Fast and Private",
    description:
      "Convert iPhone HEIC photos into JPG or WebP. Kompresio keeps the conversion workflow browser-first where supported.",
    h1: "HEIC to JPG Converter",
    eyebrow: "iPhone photo converter",
    icon: "image",
    mode: "heic",
    primaryAction: "Convert HEIC",
    primaryKeyword: "HEIC to JPG",
    category: "Conversion",
    supportedFormats: ["HEIC", "HEIF"],
    benefits: [
      "Prepare iPhone photos for systems that do not accept HEIC.",
      "Convert to JPG or WebP output where browser support allows it.",
      "Batch queue is ready for future advanced HEIC workflows.",
    ],
    steps: ["Upload HEIC files.", "Choose JPG or WebP output.", "Download converted images."],
    useCases: ["Documents", "Forms", "Marketplace uploads"],
    related: ["compress-image", "convert-to-webp", "metadata-cleaner", "batch-converter"],
    faqs: commonFaqs,
  },
  {
    slug: "metadata-cleaner",
    name: "Metadata Cleaner",
    title: "Remove Image Metadata Online — Fast and Private",
    description:
      "Remove image metadata and export clean files. Kompresio helps strip camera, software, and location-related details from photos.",
    h1: "Remove Image Metadata",
    eyebrow: "Privacy tool",
    icon: "shield",
    mode: "metadata",
    primaryAction: "Clean metadata",
    primaryKeyword: "remove image metadata",
    category: "Privacy",
    supportedFormats: ["JPG", "PNG", "WebP"],
    benefits: [
      "Re-encode images locally to remove common hidden metadata.",
      "See a practical privacy recommendation before exporting.",
      "Download clean files without account registration.",
    ],
    steps: ["Upload photos.", "Review the privacy summary.", "Export cleaned images."],
    useCases: ["Sharing photos online", "Marketplace listings", "Public documents"],
    related: ["compress-image", "resize-image", "convert-to-webp", "image-analyzer"],
    faqs: commonFaqs,
  },
  {
    slug: "batch-converter",
    name: "Batch Converter",
    title: "Batch Image Converter — Fast and Private",
    description:
      "Batch process multiple images with Kompresio. Convert, compress, resize, clean metadata, and export results as a ZIP archive.",
    h1: "Batch Image Converter",
    eyebrow: "Batch workflow",
    icon: "archive",
    mode: "batch",
    primaryAction: "Process batch",
    primaryKeyword: "batch image converter",
    category: "Batch",
    supportedFormats: ["JPG", "PNG", "WebP", "AVIF", "GIF", "SVG"],
    benefits: [
      "Process many images in one queue.",
      "Export all results as a ZIP with a summary manifest.",
      "Ideal for product catalogs, website assets, and content batches.",
    ],
    steps: ["Upload a batch.", "Choose shared output settings.", "Download all results as ZIP."],
    useCases: ["Product catalogs", "Website migrations", "Content teams"],
    related: ["compress-image", "convert-to-webp", "resize-image", "metadata-cleaner"],
    faqs: commonFaqs,
  },
  {
    slug: "image-analyzer",
    name: "Image Analyzer",
    title: "Image Analyzer Online — Size, Format, and Optimization Tips",
    description:
      "Analyze image size, dimensions, format, and optimization opportunities before compressing or converting with Kompresio.",
    h1: "Image Analyzer Online",
    eyebrow: "Optimization audit",
    icon: "search",
    mode: "analyzer",
    primaryAction: "Analyze image",
    primaryKeyword: "image analyzer",
    category: "Utility",
    supportedFormats: ["JPG", "PNG", "WebP", "AVIF", "GIF", "SVG"],
    benefits: [
      "See dimensions, file size, and format before exporting.",
      "Get smart recommendations for compression and resize.",
      "Prepare image assets for website performance work.",
    ],
    steps: ["Upload images.", "Read the recommendation.", "Apply compression, resize, or conversion."],
    useCases: ["Website audits", "SEO image prep", "Developer handoff"],
    related: ["compress-image", "convert-to-webp", "resize-image", "metadata-cleaner"],
    faqs: commonFaqs,
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    title: "Image to PDF Converter — Fast and Private",
    description:
      "Convert JPG, PNG, and WebP images into a private multi-page PDF directly in your browser with page size, orientation, margin, and quality controls.",
    h1: "Image to PDF Converter",
    eyebrow: "Document tool",
    icon: "file",
    mode: "pdf",
    primaryAction: "Create PDF",
    primaryKeyword: "image to PDF",
    category: "Utility",
    supportedFormats: ["JPG", "PNG", "WebP"],
    benefits: [
      "Combine one or many images into a single downloadable PDF.",
      "Choose A4 or Letter pages, portrait or landscape orientation, and PDF margins.",
      "Resize and compress source images before document export.",
    ],
    steps: ["Upload document images.", "Choose page size, orientation, margin, and quality.", "Create and download the PDF."],
    useCases: ["Students", "Forms", "Document uploads"],
    related: ["compress-image", "resize-image", "metadata-cleaner", "batch-converter"],
    faqs: commonFaqs,
  },
];

export const featuredTools = tools.filter((tool) =>
  ["compress-image", "convert-to-webp", "resize-image", "metadata-cleaner", "batch-converter", "image-analyzer"].includes(
    tool.slug,
  ),
);

export function getTool(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}

export function getRelatedTools(tool: ToolDefinition) {
  return tool.related
    .map((slug) => tools.find((item) => item.slug === slug))
    .filter((item): item is ToolDefinition => Boolean(item));
}
